# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
        os:
          description: 'Operating system to run on'
          required: true
          default: 'all'
          type: choice
          options:
            - all
            - ubuntu-latest
            - windows-latest
            - macos-latest

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    if: ${{ github.event_name == 'push' || inputs.os != '' }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ github.event_name == 'workflow_dispatch' && inputs.os != 'all' && fromJson('["' + inputs.os + '"]') || fromJson('["ubuntu-latest","windows-latest","macos-latest"]') }}
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
